name: Closed PR
env:
  GIT_SHA: ${{ github.sha }}
on:
  pull_request:
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
      step: ${{ steps.validate_branch.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "##[set-output name=branch;]${BRANCH_NAME:0:35}"
      - name: Check if branch name starts with 'feat/' or 'fix/'
        id: validate_branch
        run: |
          if [[ ${{ steps.extract_branch.outputs.branch }} != feat/* && ${{ steps.extract_branch.outputs.branch }} != fix/* ]]; 
          then
            echo "Branch name must start with 'feat/' or 'fix/'"
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

  destroy-preview:
    needs: setup
    if: ${{ needs.setup.outputs.step }} == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - id: auth
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          token_format: "access_token"
      - name: Terraform Destroy
        working-directory: ./infrastructure
        run: |
          terraform init
          terraform workspace select celatone-api-${{ needs.setup.outputs.branch_name }}
          terraform destroy -var-file=deploy-preview.tfvars -var="image_url=test" -var="environment=${{needs.setup.outputs.branch_name}}" -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
